export const CurrencyCountryMap = [
  {country: "AD", currency: "EUR"},
  {country: "AE", currency: "AED"},
  {country: "AF", currency: "AFN"},
  {country: "AG", currency: "XCD"},
  {country: "AI", currency: "XCD"},
  {country: "AL", currency: "ALL"},
  {country: "AM", currency: "AMD"},
  {country: "AO", currency: "AOA"},
  {country: "AQ", currency: null},
  {country: "AR", currency: "ARS"},
  {country: "AS", currency: "USD"},
  {country: "AT", currency: "EUR"},
  {country: "AU", currency: "AUD"},
  {country: "AW", currency: "AWG"},
  {country: "AX", currency: "EUR"},
  {country: "AZ", currency: "AZN"},
  {country: "BA", currency: "BAM"},
  {country: "BB", currency: "BBD"},
  {country: "BD", currency: "BDT"},
  {country: "BE", currency: "EUR"},
  {country: "BF", currency: "XOF"},
  {country: "BG", currency: "BGN"},
  {country: "BH", currency: "BHD"},
  {country: "BI", currency: "BIF"},
  {country: "BJ", currency: "XOF"},
  {country: "BL", currency: "EUR"},
  {country: "BM", currency: "BMD"},
  {country: "BN", currency: "BND"},
  {country: "BO", currency: "BOB"},
  {country: "BQ", currency: "USD"},
  {country: "BR", currency: "BRL"},
  {country: "BS", currency: "BSD"},
  {country: "BT", currency: "INR"},
  {country: "BV", currency: "NOK"},
  {country: "BW", currency: "BWP"},
  {country: "BY", currency: "BYN"},
  {country: "BZ", currency: "BZD"},
  {country: "CA", currency: "CAD"},
  {country: "CC", currency: "AUD"},
  {country: "CD", currency: "CDF"},
  {country: "CF", currency: "XAF"},
  {country: "CG", currency: "XAF"},
  {country: "CH", currency: "CHF"},
  {country: "CI", currency: "XOF"},
  {country: "CK", currency: "NZD"},
  {country: "CL", currency: "CLP"},
  {country: "CM", currency: "XAF"},
  {country: "CN", currency: "CNY"},
  {country: "CO", currency: "COP"},
  {country: "CR", currency: "CRC"},
  {country: "CU", currency: "CUP"},
  {country: "CV", currency: "CVE"},
  {country: "CW", currency: "ANG"},
  {country: "CX", currency: "AUD"},
  {country: "CY", currency: "EUR"},
  {country: "CZ", currency: "CZK"},
  {country: "DE", currency: "EUR"},
  {country: "DJ", currency: "DJF"},
  {country: "DK", currency: "DKK"},
  {country: "DM", currency: "XCD"},
  {country: "DO", currency: "DOP"},
  {country: "DZ", currency: "DZD"},
  {country: "EC", currency: "USD"},
  {country: "EE", currency: "EUR"},
  {country: "EG", currency: "EGP"},
  {country: "EH", currency: "MAD"},
  {country: "ER", currency: "ERN"},
  {country: "ES", currency: "EUR"},
  {country: "ET", currency: "ETB"},
  {country: "FI", currency: "EUR"},
  {country: "FJ", currency: "FJD"},
  {country: "FK", currency: "FKP"},
  {country: "FM", currency: "USD"},
  {country: "FO", currency: "DKK"},
  {country: "FR", currency: "EUR"},
  {country: "GA", currency: "XAF"},
  {country: "GB", currency: "GBP"},
  {country: "GD", currency: "XCD"},
  {country: "GE", currency: "GEL"},
  {country: "GF", currency: "EUR"},
  {country: "GG", currency: "GGP"},
  {country: "GH", currency: "GHS"},
  {country: "GI", currency: "GIP"},
  {country: "GL", currency: "DKK"},
  {country: "GM", currency: "GMD"},
  {country: "GN", currency: "GNF"},
  {country: "GP", currency: "EUR"},
  {country: "GQ", currency: "XAF"},
  {country: "GR", currency: "EUR"},
  {country: "GS", currency: "GBP"},
  {country: "GT", currency: "GTQ"},
  {country: "GU", currency: "USD"},
  {country: "GW", currency: "XOF"},
  {country: "GY", currency: "GYD"},
  {country: "HK", currency: "HKD"},
  {country: "HM", currency: "AUD"},
  {country: "HN", currency: "HNL"},
  {country: "HR", currency: "HRK"},
  {country: "HT", currency: "HTG"},
  {country: "HU", currency: "HUF"},
  {country: "ID", currency: "IDR"},
  {country: "IE", currency: "EUR"},
  {country: "IL", currency: "ILS"},
  {country: "IM", currency: "GBP"},
  {country: "IN", currency: "INR"},
  {country: "IO", currency: "USD"},
  {country: "IQ", currency: "IQD"},
  {country: "IR", currency: "IRR"},
  {country: "IS", currency: "ISK"},
  {country: "IT", currency: "EUR"},
  {country: "JE", currency: "GBP"},
  {country: "JM", currency: "JMD"},
  {country: "JO", currency: "JOD"},
  {country: "JP", currency: "JPY"},
  {country: "KE", currency: "KES"},
  {country: "KG", currency: "KGS"},
  {country: "KH", currency: "KHR"},
  {country: "KI", currency: "AUD"},
  {country: "KM", currency: "KMF"},
  {country: "KN", currency: "XCD"},
  {country: "KP", currency: "KPW"},
  {country: "KR", currency: "KRW"},
  {country: "KW", currency: "KWD"},
  {country: "KY", currency: "KYD"},
  {country: "KZ", currency: "KZT"},
  {country: "LA", currency: "LAK"},
  {country: "LB", currency: "LBP"},
  {country: "LC", currency: "XCD"},
  {country: "LI", currency: "CHF"},
  {country: "LK", currency: "LKR"},
  {country: "LR", currency: "LRD"},
  {country: "LS", currency: "LSL"},
  {country: "LT", currency: "EUR"},
  {country: "LU", currency: "EUR"},
  {country: "LV", currency: "EUR"},
  {country: "LY", currency: "LYD"},
  {country: "MA", currency: "MAD"},
  {country: "MC", currency: "EUR"},
  {country: "MD", currency: "MDL"},
  {country: "ME", currency: "EUR"},
  {country: "MF", currency: "EUR"},
  {country: "MG", currency: "MGA"},
  {country: "MH", currency: "USD"},
  {country: "MK", currency: "MKD"},
  {country: "ML", currency: "XOF"},
  {country: "MM", currency: "MMK"},
  {country: "MN", currency: "MNT"},
  {country: "MO", currency: "MOP"},
  {country: "MP", currency: "USD"},
  {country: "MQ", currency: "EUR"},
  {country: "MR", currency: "MRO"},
  {country: "MS", currency: "XCD"},
  {country: "MT", currency: "EUR"},
  {country: "MU", currency: "MUR"},
  {country: "MV", currency: "MVR"},
  {country: "MW", currency: "MWK"},
  {country: "MX", currency: "MXN"},
  {country: "MY", currency: "MYR"},
  {country: "MZ", currency: "MZN"},
  {country: "NA", currency: "NAD"},
  {country: "NC", currency: "XPF"},
  {country: "NE", currency: "XOF"},
  {country: "NF", currency: "AUD"},
  {country: "NG", currency: "NGN"},
  {country: "NI", currency: "NIO"},
  {country: "NL", currency: "EUR"},
  {country: "NO", currency: "NOK"},
  {country: "NP", currency: "NPR"},
  {country: "NR", currency: "AUD"},
  {country: "NU", currency: "NZD"},
  {country: "NZ", currency: "NZD"},
  {country: "OM", currency: "OMR"},
  {country: "PA", currency: "PAB"},
  {country: "PE", currency: "PEN"},
  {country: "PF", currency: "XPF"},
  {country: "PG", currency: "PGK"},
  {country: "PH", currency: "PHP"},
  {country: "PK", currency: "PKR"},
  {country: "PL", currency: "PLN"},
  {country: "PM", currency: "EUR"},
  {country: "PN", currency: "NZD"},
  {country: "PR", currency: "USD"},
  {country: "PS", currency: "JOD"},
  {country: "PT", currency: "EUR"},
  {country: "PW", currency: "USD"},
  {country: "PY", currency: "PYG"},
  {country: "QA", currency: "QAR"},
  {country: "RE", currency: "EUR"},
  {country: "RO", currency: "RON"},
  {country: "RS", currency: "RSD"},
  {country: "RU", currency: "RUB"},
  {country: "RW", currency: "RWF"},
  {country: "SA", currency: "SAR"},
  {country: "SB", currency: "SBD"},
  {country: "SC", currency: "SCR"},
  {country: "SD", currency: "SDG"},
  {country: "SE", currency: "SEK"},
  {country: "SG", currency: "SGD"},
  {country: "SH", currency: "SHP"},
  {country: "SI", currency: "EUR"},
  {country: "SJ", currency: "NOK"},
  {country: "SK", currency: "EUR"},
  {country: "SL", currency: "SLL"},
  {country: "SM", currency: "EUR"},
  {country: "SN", currency: "XOF"},
  {country: "SO", currency: "SOS"},
  {country: "SR", currency: "SRD"},
  {country: "SS", currency: "SSP"},
  {country: "ST", currency: "STD"},
  {country: "SV", currency: "USD"},
  {country: "SX", currency: "ANG"},
  {country: "SY", currency: "SYP"},
  {country: "SZ", currency: "SZL"},
  {country: "TC", currency: "USD"},
  {country: "TD", currency: "XAF"},
  {country: "TF", currency: "EUR"},
  {country: "TG", currency: "XOF"},
  {country: "TH", currency: "THB"},
  {country: "TJ", currency: "TJS"},
  {country: "TK", currency: "NZD"},
  {country: "TL", currency: "USD"},
  {country: "TM", currency: "TMT"},
  {country: "TN", currency: "TND"},
  {country: "TO", currency: "TOP"},
  {country: "TR", currency: "TRY"},
  {country: "TT", currency: "TTD"},
  {country: "TV", currency: "AUD"},
  {country: "TW", currency: "TWD"},
  {country: "TZ", currency: "TZS"},
  {country: "UA", currency: "UAH"},
  {country: "UG", currency: "UGX"},
  {country: "UM", currency: "USD"},
  {country: "US", currency: "USD"},
  {country: "UY", currency: "UYU"},
  {country: "UZ", currency: "UZS"},
  {country: "VA", currency: "EUR"},
  {country: "VC", currency: "XCD"},
  {country: "VE", currency: "VEF"},
  {country: "VG", currency: "USD"},
  {country: "VI", currency: "USD"},
  {country: "VN", currency: "VND"},
  {country: "VU", currency: "VUV"},
  {country: "WF", currency: "XPF"},
  {country: "WS", currency: "EUR"},
  {country: "YE", currency: "YER"},
  {country: "YT", currency: "EUR"},
  {country: "ZA", currency: "ZAR"},
  {country: "ZM", currency: "ZMW"},
  {country: "ZW", currency: "USD"},
];

export const isoCountries: Record<string, string> = {
  AF: "Afghanistan",
  AX: "Aland Islands",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua And Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia And Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei Darussalam",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Congo, Democratic Republic",
  CK: "Cook Islands",
  CR: "Costa Rica",
  CI: "Cote D'Ivoire",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FK: "Falkland Islands (Malvinas)",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern Territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island & Mcdonald Islands",
  VA: "Holy See (Vatican City State)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran, Islamic Republic Of",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle Of Man",
  IL: "Israel",
  IT: "Italy",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KR: "Korea",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Lao People's Democratic Republic",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libyan Arab Jamahiriya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MK: "Macedonia",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia, Federated States Of",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  AN: "Netherlands Antilles",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestinian Territory, Occupied",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RU: "Russian Federation",
  RW: "Rwanda",
  BL: "Saint Barthelemy",
  SH: "Saint Helena",
  KN: "Saint Kitts And Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin",
  PM: "Saint Pierre And Miquelon",
  VC: "Saint Vincent And Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome And Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia And Sandwich Isl.",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard And Jan Mayen",
  SZ: "Swaziland",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syrian Arab Republic",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad And Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks And Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UM: "United States Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Viet Nam",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  WF: "Wallis And Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};
